- name: Get installed packages (RedHat-based)
  command: rpm -qa
  register: package_list
  when: ansible_facts['os_family'] == "RedHat"

- name: Save package list as fact
  set_fact:
    package_text: "{{ package_list.stdout }}"
  when: package_list is defined
